---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mywebapp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mywebapp
 template:
  metadata: 
   labels:
    app: mywebapp
  spec:
   containers:
   - name: mywebapp
     image: gcr.io/leafy-oxide-260319/mywebappgcr:tag
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  type: LoadBalancer
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 7676
      targetPort: 8080
