---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mywebappgcr
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mywebappgcr
 template:
  metadata: 
   labels:
    app: mywebappgcr
  spec:
   containers:
   - name: mywebappgcr
     image: gcr.io/leafy-oxide-260319/mywebappgcr:tag
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mywebappgcr
spec:
  type: LoadBalancer
  selector:
    app: mywebappgcr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 8080
